version: '3.5'

services:

  k8s.gcr.io:
    image: registry:2
    hostname: k8s.gcr.io
    container_name: k8s.gcr.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - vol-registries:/var/lib/registry
    networks:
      - net-registries

  gcr.io:
    image: registry:2
    hostname: gcr.io
    container_name: gcr.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - vol-registries:/var/lib/registry
    networks:
      - net-registries

  quay.io:
    image: registry:2
    hostname: quay.io
    container_name: quay.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - vol-registries:/var/lib/registry
    networks:
      - net-registries

  mr.io:
    image: registry:2
    hostname: mr.io
    container_name: mr.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    ports:
      - "5000:80"
    volumes:
      - vol-registries:/var/lib/registry
    networks:
      - net-registries

  docker.io:
    image: registry:2
    hostname: registry-1.docker.io
    container_name: registry-1.docker.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry-1.docker.io.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry-1.docker.io.key
    volumes:
      - ./install/certs:/certs
      - vol-registries:/var/lib/registry
    networks:
      - net-registries

  socat:
    image: alpine/socat
    command:
      tcp-listen:443,fork tcp-connect:registry-1.docker.io:443
    ports:
      - "443:443"
    networks:
      - net-registries

volumes:
  vol-registries:
    name: vol-registries
    external: true

networks:
  net-registries:
    name: net-registries
    driver: bridge
    external: true
