version: '3.5'

services:

  k8s.gcr.io:
    image: registry:2
    hostname: k8s.gcr.io
    container_name: k8s.gcr.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - vol-mr.io:/var/lib/registry
    networks:
      - net-registry

  gcr.io:
    image: registry:2
    hostname: gcr.io
    container_name: gcr.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - vol-mr.io:/var/lib/registry
    networks:
      - net-registry

  quay.io:
    image: registry:2
    hostname: quay.io
    container_name: quay.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - vol-mr.io:/var/lib/registry
    networks:
      - net-registry

  mr.io:
    image: registry:2
    hostname: mr.io
    container_name: mr.io
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    ports:
      - "5000:80"
    volumes:
      - vol-mr.io:/var/lib/registry
    networks:
      - net-registry

  docker.io-mirror:
    image: registry:2
    hostname: docker.io-mirror
    container_name: docker.io-mirror
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    ports:
      - "5555:80"
    volumes:
      - vol-mr.io:/var/lib/registry
    networks:
      - net-registry

volumes:
  vol-mr.io:
    name: vol-mr.io
    external: true

networks:
  net-registry:
    name: net-registry
    driver: bridge
    external: true
