---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apic-ana-data
  labels:
    type: local
spec:
  storageClassName: apic-local-storage
  capacity:
    storage: @@data_storage_size_gbGi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/elasticsearch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apic-ana-master-data
  labels:
    type: local
spec:
  storageClassName: apic-local-storage
  capacity:
    storage: @@master_storage_size_gbGi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/elasticsearch
