apiVersion: v1
kind: PersistentVolume
metadata:
  name: apic-mgmt-cassandra
  labels:
    type: local
spec:
  storageClassName: apic-local-storage
  capacity:
    storage: @@cassandra_volume_size_gbGi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: @@apic_pv_homevar/db
