apiVersion: v1
kind: PersistentVolume
metadata:
  name: apic-mgmt-cassandra
spec:
  capacity:
    storage: @@cassandra_volume_size_gbGi
  storageClassName: apic-local-storage
  local:
    path: /var/db
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: ["kube-node-1"]
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
